-- Inov@Rede Saúde 360 - estrutura inicial da Área do Aluno
-- Execute no SQL Editor do Supabase depois de revisar.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_url text,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text,
  video_url text,
  material_url text,
  position integer not null default 1,
  published boolean not null default false
);

create table if not exists public.enrollments (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  primary key (user_id, course_id)
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  primary key (user_id, lesson_id)
);

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;

revoke all on table public.profiles, public.courses, public.lessons, public.enrollments, public.lesson_progress from anon;
grant select, insert, update on table public.profiles to authenticated;
grant select on table public.courses, public.lessons to authenticated;
grant select, insert on table public.enrollments to authenticated;
grant select, insert, update on table public.lesson_progress to authenticated;

create policy "Aluno consulta o próprio perfil" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "Aluno cria o próprio perfil" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "Aluno atualiza o próprio perfil" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "Autenticados consultam cursos publicados" on public.courses for select to authenticated using (published = true);
create policy "Autenticados consultam aulas publicadas" on public.lessons for select to authenticated using (published = true);
create policy "Aluno consulta suas matrículas" on public.enrollments for select to authenticated using ((select auth.uid()) = user_id);
create policy "Aluno realiza a própria matrícula" on public.enrollments for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Aluno consulta o próprio progresso" on public.lesson_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "Aluno registra o próprio progresso" on public.lesson_progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Aluno atualiza o próprio progresso" on public.lesson_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
